#include truc
//#include includeTest.idl
#include pouet.idl
#import test2.idl
#include test.idl

component Philosopher : pouet {
  attribute bool name;
  // The left fork receptacle.
  uses int left;
  // The right fork receptacle.
  uses int right;
// The status info event source.
publishes StatusInfo info;
exception InUse {};
void get() raises (/* InUse,anotherOne*/);
void release(in int p, out int f , inout int e);
};


// Le composant
component ForkManager {
  // Facette utilisé par les phisolphes.
  provides Fork the_fork;
};
