exception InUse{};

interface Fork{
  void get() raises (InUse);
  void release();
};

component Fork_Item{
  provides Fork the_fork;
};

component Philosopher{
  attribute string  name;
  uses Fork_Item left;
  uses Fork_Item right;
};
